<B>Importing libraries</B>

In [ ]:
import os
from skimage import data
import numpy as np
from pandas import DataFrame
from sklearn.model_selection import train_test_split

In [ ]:
from scipy import misc
import os
from PIL import Image
import scipy.misc
import imageio
from skimage.transform import rescale, resize
from matplotlib import pyplot as plt

<b>Setting path</b>

In [ ]:
cd C:\Users\global\python

C:\Users\global\python


<b>creating X and y</b>

In [ ]:
from skimage import io
X=[]
y=[]
base_path='./Covid_dataset'
source_path=base_path
for child in os.listdir(source_path):
    print(child)
    sub_path = os.path.join(source_path, child)
    bsub_path = os.path.join(base_path, child)
    if os.path.isdir(sub_path):
        count=0
        for data_file in os.listdir(sub_path):
            Qry = Image.open(os.path.join(sub_path, data_file))
            Qry =Qry.convert("L")
            Qry = np.array(Qry.resize((224,224)))
            Qry = Qry.reshape([224,224,1])
            flist=np.array(Qry)
            X.append(flist)
            y.append(child)

Covid
NORMAL
PNEUMONIA


In [ ]:
X

[array([[[132],
         [121],
         [113],
         ...,
         [135],
         [140],
         [236]],
 
        [[102],
         [ 92],
         [ 86],
         ...,
         [124],
         [130],
         [234]],
 
        [[ 53],
         [ 47],
         [ 47],
         ...,
         [117],
         [124],
         [233]],
 
        ...,
 
        [[246],
         [243],
         [242],
         ...,
         [214],
         [212],
         [247]],
 
        [[245],
         [243],
         [242],
         ...,
         [215],
         [215],
         [247]],
 
        [[246],
         [244],
         [243],
         ...,
         [222],
         [221],
         [249]]], dtype=uint8),
 array([[[ 51],
         [ 52],
         [ 50],
         ...,
         [ 49],
         [ 49],
         [ 50]],
 
        [[ 51],
         [ 51],
         [ 51],
         ...,
         [ 49],
         [ 49],
         [ 49]],
 
        [[ 52],
         [ 51],
         [ 51],
         ...,
      

In [ ]:
y

['Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',
 'Covid',


In [ ]:
images_arr = np.asarray(X)
images_arr = images_arr.astype('float32')
images_arr = images_arr / np.max(images_arr)

In [ ]:
X=[]
for i in range(images_arr.shape[0]):
    img= resize(images_arr[i] ,(224,224,1),anti_aliasing=True)
    X.append(img)

In [ ]:
X=np.asarray(X)
X = X.astype('float32')
from sklearn.preprocessing import LabelBinarizer
labelBinarizer = LabelBinarizer()
y=labelBinarizer.fit_transform(y)
print(y)

[[1 0 0]
 [1 0 0]
 [1 0 0]
 ...
 [0 0 1]
 [0 0 1]
 [0 0 1]]


In [ ]:
y.shape

(695, 3)

In [ ]:
X.shape

(695, 224, 224, 1)

<b> spliting training and testing set</b>

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

In [ ]:
len(X_train)
len(y_train)

556

In [ ]:
y_train.shape[1]

3

In [ ]:
y_train

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       ...,
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0]])

<b> Importing models</b>

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Activation,Flatten,Dropout
import random
import tensorflow as tf
from tensorflow.keras.optimizers import SGD

In [ ]:
import keras
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.layers import BatchNormalization
from tensorflow.keras.layers import Input,Conv2D,MaxPooling2D,Conv2DTranspose

<b>Define the model</b>

In [ ]:
random.seed(42)
np.random.seed(42)
tf.random.set_seed(42)
cnnModel= Sequential()
cnnModel.add(Conv2D(64, (5,5) , padding = 'same', activation="relu", input_shape=(224,224,1)))
cnnModel.add(Conv2D(64, (5,5) , padding = 'same', activation="relu"))
cnnModel.add(Conv2D(64, (5,5) , padding = 'same', activation="relu"))
cnnModel.add(MaxPooling2D((2,2)))
cnnModel.add(Conv2D(128, (5,5) , padding = 'same', activation="relu"))
cnnModel.add(Conv2D(128, (5,5) , padding = 'same', activation="relu"))
cnnModel.add(MaxPooling2D((2,2)))
cnnModel.add(Conv2D(128, (5,5) , padding = 'same', activation="relu"))
cnnModel.add(Conv2D(128, (5,5) , padding = 'same', activation="relu"))
cnnModel.add(Conv2D(128, (5,5) , padding = 'same', activation="relu"))
cnnModel.add(MaxPooling2D((2,2)))
cnnModel.add(Flatten())
cnnModel.add(Dense(100,activation="relu"))
cnnModel.add(Dense(200,activation="relu"))
cnnModel.add(Dense(3,activation="softmax"))
cnnModel.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_11 (Conv2D)          (None, 224, 224, 64)      1664      
                                                                 
 conv2d_12 (Conv2D)          (None, 224, 224, 64)      102464    
                                                                 
 conv2d_13 (Conv2D)          (None, 224, 224, 64)      102464    
                                                                 
 max_pooling2d_4 (MaxPooling  (None, 112, 112, 64)     0         
 2D)                                                             
                                                                 
 conv2d_14 (Conv2D)          (None, 112, 112, 128)     204928    
                                                                 
 conv2d_15 (Conv2D)          (None, 112, 112, 128)     409728    
                                                      

<b>Complie the model</b>

In [ ]:
sgd = SGD(learning_rate=0.01)

In [ ]:
cnnModel.compile(optimizer='sgd',loss="categorical_crossentropy",metrics=["accuracy"])

<b>Fit the model</b>

In [ ]:
cnnModel.fit(X_train,y_train,epochs=10,batch_size=64,verbose=1,validation_split=0.1)

Epoch 1/10


<b>Evaluate Model</b>

In [ ]:
testLoss, testAccuracy = dnnModel.evaluate(X_test,y_test)
print("Test Accuracy =", testAccuracy)

<b> GUI Using Tkinter</b>

In [ ]:
import tkinter as tk
from tkinter import filedialog
from tkinter.filedialog import askopenfile
from PIL import Image, ImageTk

In [ ]:
my_w = tk.Tk()

<b> Upload image and Predict the class it belongs</b>

In [ ]:
my_w.geometry("700x1000")
my_w.title('deep learning assignment')
my_w.maxsize(800,300)
my_font1=('times', 18, 'bold')
l1 = tk.Label(my_w,text='Diagnosis of Pneumonia and covid19 from Chest X-Ray Images ',width=50,font=my_font1)  
l1.grid(row=1,column=2)
b1 = tk.Button(my_w, text='Upload File',width=20,command = lambda:upload_file())
b1.grid(row=2,column=2) 

def upload_file():
    global img
    f_types = [('Jpg Files', '*.jpeg')]
    filename = filedialog.askopenfilename(filetypes=f_types)
    Qry = Image.open(filename)
    img=Qry.resize((224,224))
    Qry =Qry.convert("L")
    Qry = np.array(Qry.resize((224,224)))
    Qry = Qry.reshape([1,224,224])
    flist=np.array(Qry)
    #array
    flist=np.asarray(flist)
    flist=flist.astype('float32')
    flist= flist.reshape([1,224,224])
    flist= flist/np.max(flist)
    flist=flist.reshape((*flist.shape[:-2], -1))
    y_predict=dnnModel.predict(flist)
    pred = labelBinarizer.inverse_transform(y_predict)
    b2 =tk.Label(text=str(pred),font=my_font1)# using Button predict class
    b2.grid(row=3,column=2)
    b3=tk.Label(text="the probability of each class"+str(y_predict),font=my_font1)
    b3.grid(row=5,column=2)
    img = ImageTk.PhotoImage(img)
    b4 =tk.Button(my_w,image=img) # using Button 
    b4.grid(row=6,column=2)

my_w.mainloop()  # Keep the window open